### ISSUE TITLE
More than one db on a server

### ISSUE THREAD

**Issue by rayrebel** [ikzelf/zbxora#12]
How to configure hostname in the configuration file if more than one db instance is on a server? There must be hostname for each db instance?

**Comment by ikzelf** [comment]
yes, a database is in terms of zabbix, a host. Oracle databases can have multiple instances(RAC) but still is 1 database.

**Comment by rayrebel** [comment]
Thank you for you answer. I'd like to ask some question:
Does it mean that we must create the Zabbix host for each db instance (we have hundreds of db instances)?
Is it possible to identify which database or which db instance is on which server?

**Comment by ikzelf** [comment]
Well, yes, you need to create a zabbix host and connect the template to it, for every database on your system. Yes, it is possible to see on which machine database instance[s] are running. For large amounts of databases you could create a discovery script that effectively takes care for the zabbix hosts creation for your databases. For that you need to figure out where it makes sense to run the discovery for all your databases. Problem is that zabbix want to discover them all together so you must do that in a central location. You could use a simple list that you maintain and feed to zabbix using zabbix_sender. This works OK. If you run zbxora.py from a single client to monitor all databases, that client would be a nice option. zbxora.py can better be run from a client than from a db server ..... It uses regular sql*net access to the databases.
If you have more idea's to make zbxora more usefull, please, go ahead and tell them ...

**Comment by ikzelf** [comment]
Hi Sergio,

if this is meant to be to automate hosts generation/ database discovery, I think this can be done a little smarter. Most sites have multiple database servers so on the monitoring host just collect all database servers from which you want to discover the databases that run on them. A separate process needs to visit those machines every once and a while to collect the known/running databases and store the results on the monitoring host. A zabbix upload script needs to combine all results and send them in one big lld array to zabbix.
In zabbix you can use host prototypes to do the hosts generation for you. From zabbix point of view, each db is a host.

A lot of site specifics do play a role here. For example, some run RAC, some don't. If a site runs RAC, multiple hosts will return the same database (because the instances run on different hosts). Some sites have a unique name for each and every database, some use only a few names and have many duplicates. For a RAC database, zbxora uses 1 connection to one of the instances and monitors all instances using the Global views. A RAC database with 3 instances is just one host in zabbix.

Maybe easiest is to just generate a list of the running instances on every host, collect them in a instances collection location and have a process connect to all those instances to find out which instances belong to the same group of instances (and doing so are part of the same RAC database). Normally with a list like host:ORACLE_SID:DBNAME you should be able to do something sensible.

It is not simple to do this in a way that it fit's for all. For me a reason not to create it but as always, I am open for suggestions.

**Comment by ikzelf** [comment]
Hi Sergio,
if it is all working OK now and if you think it would be valuable for others, why don't you just issue a pull request for your code? In that case the readme also needs some extra notes.

Currently I am just a bit to busy to work on extra projects ...

**Comment by ikzelf** [comment]
I just uploaded zbx_discover_oradbs that has the task to discover all databases using etc/zbx_discover_oradba.cfg as input for the machines to logon to to check the listener that is running on that node. It should be run by the oracle owner .... and can deliver a json file that should be usable for lld.
