### ISSUE TITLE
Help zabbix_sender and zabbix_started

### ISSUE THREAD

**Issue by thanhtuan** [ikzelf/zbxora#20]
Hi ikzelf
I have problem , sorry my english not good

1. using checks from ['/root/ciber/etc/zbxora_checks/oracle/primary.12.cfg', '/root/ciber/etc/zbxora_checks/oracle/sap.cfg', '/root/ciber/etc/zbxora_checks/oracle/ebs.cfg']
checks loading /root/ciber/etc/zbxora_checks/oracle/primary.12.cfg
checks loading /root/ciber/etc/zbxora_checks/oracle/sap.cfg
checks loading /root/ciber/etc/zbxora_checks/oracle/ebs.cfg
20auto_discovery_1000 run every 1000 minutes
              expu.lld: select decode (s.con_id,0, d.name, p.name) "{#PDB}", usernam
              ustat.lld: select decode (s.con_id,0, d.name, p.name) "{#PDB}", account
      auto_discovery_60 run every 60 minutes
              arl_dest.lld: select i.instance_name "{#INST_NAME}",d.dest_name "{#ARL_DES
              db.lld: select name "{#PDB}" from v$pdbs union select name from v$da
              ...
              ebs.bagger: select * from gg
 key=ebs_10m.ebs.concmgr ORA-942: Db execution error: ORA-00942: table or view does not exist
 key=ebs_10m.ebs.paul.truncatp ORA-942: Db execution error: ORA-00942: table or view does not exist
 key=ebs_60m.concmanager ORA-942: Db execution error: ORA-00942: table or view does not exist
 key=ebs_discovery_60m.ebs.concmanager ORA-942: Db execution error: ORA-00942: table or view does not exist
 key=ebs_startup.ebs.bagger ORA-942: Db execution error: ORA-00942: table or view does not exist

i have run scrips : python3.6 zbxora.py -c $HOME/ciber/etc/zbxora.fsdb02.cfg
and I don't knowso has obtained the data from Oracle database or none?

2. please point me to configure zabbix-sender. I cant

thank you so much

**Comment by thanhtuan** [comment]
When I run zbx-started

[root@oracleclient bin]# ./zbxora_starter
mon etc/zbxora.cluster1-ASM.cfg 1
mon etc/zbxora.fsdb02.cfg root 6785 2525 0 22:52 pts/1 00:00:00 python3.6 zbxora.py -c /root/ciber/etc/zbxora.fsdb02.cfg 0

Im no edit file  zbxora_starter and zbxora_sender

**Comment by ikzelf** [comment]
Hi thanhtuan,

1) it looks like you left the site_checks parameter in place. This was intended as an example only  so the error you get are bacause you have no ebs application in your database.
2) it is  smarter to switch  to zbxdb since I no longer maintain zbxora. zbxdb is the  multi vendor replacement for zbxora, with the same functionality.
3) zbxora_starter looks -default- in $HOME/etc/ for the monitor configuration files. It does source the $HOME/.bash_profile for environment settings like ZBXORA_HOME

I hope this helps,
Ronald.

**Comment by ikzelf** [comment]
move to zbxdb
