### ISSUE TITLE
I tried to read your source code,but I failed.

### ISSUE THREAD

**Issue by oraant** [ikzelf/zbxora#4]
OMG, It's so hard to read it with out any annotation!
And I can't find any useful function or class in it!
You win,bro,you win.(-_-)

**Comment by ikzelf** [comment]
yes, I agree, that's why I need someone to help/coach me to clean this up ;-) I do not call myself a programmer ....

**Comment by hdbsystems** [comment]
Hi,

  I have a modified version based on version 1.04 with lots of comments.  The basic logic was modified a little. I can share if you want.

best regards,
  sergio souza

**Comment by ikzelf** [comment]
Hi Sergio,
can you describe what you changed in the basic logic?
Sure, I would like to see that code. As I told before .... I am sure the code can have some improvements on readability. Technically my code has proven to be rock solid, no peformance issues, no memory leaking and some instances of zbxora are running as long as the hosts where they run on. Some have more than a year uptime now.

**Comment by hdbsystems** [comment]
Hi Ronald,
  Your code was very well written.
  After I understood the logic, I made only minor changes and changed some things in place.

[zbxora.txt](https://github.com/ikzelf/zbxora/files/782993/zbxora.txt)
[zbxora.py.txt](https://github.com/ikzelf/zbxora/files/782994/zbxora.py.txt)

best regards,
  sergio souza

**Comment by ikzelf** [comment]
Hi Sergio,

for me it looks like you certainly did some nice cleaning up of my code. I still have to test to figure out what your additions actually do.

The way I created it, was such that every database has 1 connection and that 1 connection is kept as long as possible.
If there is only one zbxora process on a machine, it could be smart to directly call zabbix_sender (I now launch that for every activation (not very efficient if you ask me))
If there are more zbxora processes running on a machine (as will often be the case since every db needs 1) I write to a directory and have zbxora_sender collect the files and upload them to zabbix using zabbix_sender in batches.
There is no hard coding of any metric in zbxora. All metrics are formed in the sql files to allow for easiest modifications and additions of new metrics, while allowing for site and or application specific metrics. See the etc/zbxora_checks/{vendor}/{checks} more as an example and a good start than as THE truth.


There are several ways of implementing auto discovery of databases and generate zabbix hosts automagically.
1) use the collection of zbxora.{DB_NAME}.cfg as truth and generate a lld array from them
2) have processes on the databases nodes discover the pmon processes and collect those lists on the monitoring hosts where a process generates a lld array from them

1) is simplest to build
2) is closer to the truth of running databases and gives alerts when configurations are missing (a host is generated, template attached and nodata alerts start coming soon)

Currently I am a bit busy, fighting projects and trying to regain health, which seem to be conflicting ….

best regards,
Ronald.

**Comment by ikzelf** [comment]
Hi Sergio,
I have been running a small test with your modified code. What I see is that you send a zbxora.database.lld. I do not think that this will work as you mean it to work. If your goal is to discover all databases in your network, you need processes that somehow list them all together and upload a lld array in 1 single run. This way, zabbix can find that databases are new, or have been removed.  The plugin databases that can exist in a container database, they are already handled. Those I do not consider as separate databases, the belong to one container and in that regard, the only for the container you need a zabbix host.
I think it is better to remove that lld code since this needs to be done in a separate process that is able to oversee all databases that you want to monitor. In this I assume you want to monitor databases that run on many machines. They can all be monitored by zbxora running on a monitoring host that is just a client for your databases.

**Comment by hdbsystems** [comment]
You are right. This code still does not discover all the databases. But this is my intention and I am currently making adjustments to achieve this goal.
At first I thought there would have to be a separate process to do the discoveries, as you wrote. But I think I've found a solution by having each discovery written to a single file and shared by all zbxora processes to that server.
Few lines will be added in the part of the code where discoveries are output (both zbxora discoveries and database queries discoveries)

I think something like this

lock discovery filename
decode JSON from discovery filename
append to OBJECTS_LIST (avoid duplicate keys)
serialize OBJECTS_LIST as JSON formatted stream to fp
** OBJECTS_JSON = '{\"data\":' + json.dumps(OBJECTS_LIST) + '}'
** output(HOSTNAME, key, OBJECTS_JSON)
unlock discovery filename

** code exists

**Comment by hdbsystems** [comment]
Hi Ronald,

  I put some code to aggregate discoveries from all zbxora monitoring databases on one server.

  I have one customer that have 15 instances running on server (production). Crazy, but...

  I´m testing now.

  See complete code. Please add SimpleFlock class.

  See piece of code:

 Code added to lock file and aggregate discoveryin bold 

                                            # discovery
                                            if "discover" in section:

                                                **# only one zbxORA process can read/write discovery file
                                                with SimpleFlock("/tmp/" + HOSTNAME + "-" + key + ".lock", timeout = 60):**

                                                    OBJECTS_LIST = []

                                                    **try:
                                                        # read discovery file 
                                                        with open(OUT_DIR + "/" + HOSTNAME + "-" + key, "r") as infile:
                                                            OBJECTS_LIST = json.load(infile)
                                                    except IOError as e:
                                                        # create discovery file if not exists 
                                                        with open(OUT_DIR + "/" + HOSTNAME + "-" + key, "w") as outfile:
                                                            json.dump(OBJECTS_LIST, outfile)**

                                                    # append with query results
                                                    for row in rows:
                                                        D = collections.OrderedDict()
                                                        for col in range(0, len(CURS.description)):
                                                            D[CURS.description[col][0]] = row[col]
                                                        OBJECTS_LIST.append(D)

                                                    **# remove duplicates from list
                                                    OBJECTS_LIST = json.loads(json.dumps(OBJECTS_LIST))
                                                    OBJECTS_LIST_UNIQUE = [dict(s) for s in set(frozenset(d.items()) for d in OBJECTS_LIST)]

                                                    # write discovery file 
                                                    with open(OUT_DIR + "/" + HOSTNAME + "-" + key, "w") as outfile:
                                                        json.dump(OBJECTS_LIST_UNIQUE, outfile)**

                                                    OBJECTS_JSON = '{\"data\":' + json.dumps(OBJECTS_LIST_UNIQUE) + '}'

                                                    # output
                                                    output(HOSTNAME, key, OBJECTS_JSON)
                                                    if DEBUG == 1: debug(HOSTNAME, key, OBJECTS_JSON, numtab=3)


  Many thanks for your comments.

best regards,
  Sergio Souza

[zbxora.py.txt](https://github.com/ikzelf/zbxora/files/795011/zbxora.py.txt)



[simpleflock.py.txt](https://github.com/ikzelf/zbxora/files/795008/simpleflock.py.txt)

**Comment by ikzelf** [comment]
I put the database discovery in a separate script.
